name: 'Run Cypress Tests'
description: 'Runs Cypress tests and generates JUnit results'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  test-results-path:
    description: 'Path to the test results file'
    required: true
    default: 'results.xml'
outputs:
  results:
    description: "Test results"
