name: Run Cypress Tests

on:
  repository_dispatch:
    types: run-tests

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        id: cypress
        run: |
          npm run test -- --reporter junit --reporter-options "mochaFile=results.xml"
          echo "::set-output name=results::$(cat results.xml)"
