name: Run Cypress Tests

on:
  repository_dispatch:
    types: do-something

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        id: cypress
        run: |
          npm run test -- --reporter junit --reporter-options "mochaFile=results.xml"
          echo "::set-output name=results::$(cat results.xml)"

      - name: Send Test Results via Webhook
        if: always()
        run: |
          payload=$(jq -n \
            --arg wf "Run Cypress Tests" \
            --arg st "${{ job.status }}" \
            --arg rs "${{ steps.cypress.outputs.results }}" \
            '{workflow: $wf, status: $st, failedSteps: $rs}')
          curl -X GET 'https://n8n.adtractive.io/webhook-test/3a51a4fa-ff2b-4ecb-b954-cc4dfea545e6' -H 'Content-Type: application/json' -d "$payload"
